version: '3.1'

services:
    eurekaserver:
        image: akshaypawaskar/eureka
        ports:
            - "8761:8761"
    zipkinserver:
        image: akshaypawaskar/zipkin-svr
        ports:
            - "9411:9411"

    my-rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"

    mongo:
        image: mongo
        ports:
            - "27017:27017"

    redisserver:
        image: redis
        ports:
            - "6379:6379"

    mysqlserver:
        image: vehicle-locator-mysql
        ports:
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: "password"

    vehicle-locator-spring-cloud-publisher:
        image: akshaypawaskar/spring-cloud-publisher
        ports:
            - "8082:8082"
        environment: 
            spring.profiles.active: "docker"
        depends_on:
            - eurekaserver
            - zipkinserver
            - my-rabbitmq
 
    websocket-spring-cloud-subscriber:
        image: akshaypawaskar/websocket-spring-cloud-subscriber
        environment: 
            spring.profiles.active: "docker"
        depends_on:
            - eurekaserver
            - zipkinserver
            - my-rabbitmq

    vehicle-locator-websocket:
        image: akshaypawaskar/vehicle-locator-websocket
        ports:
            - "8084:8084"
        environment: 
           spring.profiles.active: "docker"
        depends_on:
            - eurekaserver
            - zipkinserver

    route-service:
        image: akshaypawaskar/route-service
        environment:
            spring.profiles.active: "docker"  
        ports:
            - "8083:8083"        
        depends_on:
            - mongo

    route-service-spring-cloud-subscriber:
        image: akshaypawaskar/route-service-spring-cloud-subscriber
        environment: 
            spring.profiles.active: "docker"
        depends_on:
            - eurekaserver
            - zipkinserver
            - my-rabbitmq

    vehicle-locator-management-rest:
        image: akshaypawaskar/vehicle-locator-management-rest
        environment: 
            spring.profiles.active: "docker"
        ports:
             - "8085:8085"
        depends_on:
            - eurekaserver
            - zipkinserver

    cache-service:
        image: akshaypawaskar/cache-service
        environment: 
            spring.profiles.active: "docker"
        ports:
             - "8088:8088"
        depends_on:
            - eurekaserver
            - zipkinserver
            - redisserver

    vehicle-locator-angular-app:
        image: akshaypawaskar/vehicle-locator-angular-app
        ports:
             - "80:80"

    vehicle-locator-simulator-angular-app:
        image: akshaypawaskar/vehicle-locator-simulator-angular-app
        ports:
             - "4201:80"             